import { creators, players } from '../../data/players';
import { AppLink } from '../ui/AppLink';
import { Button } from '../ui/Button';

export function AboutSection() {
  return (
    <section id="about" className="about-page" aria-labelledby="about-title">
      <div className="shell">
        <div className="about-opening"><div><span className="section-kicker">About / SHUSH</span><h1 id="about-title">Pequena equipa.<br /><span>Identidade inteira.</span></h1></div><div className="about-brand-panel"><div className="about-brand-image"><img src="/assets/brand/shush-logo.webp" width="1167" height="647" alt="Logótipo SHUSH" decoding="async" /></div><p>A SHUSH nasceu da ideia mais simples: um grupo de amigos, um lobby e a vontade de continuar a jogar juntos. Hoje, esse espírito vive no VALORANT, nos creators e no Drop 01.</p><div className="about-counts"><span><strong>{players.length}</strong> jogadores</span><span><strong>{creators.length}</strong> creators</span></div></div></div>
        <section className="about-origin" aria-labelledby="origin-title"><span className="section-kicker">01 / A NOSSA ORIGEM</span><div><h2 id="origin-title">Começou num lobby.<br /><span>Ficou muito para além dele.</span></h2><p>Primeiro, havia só a vontade de juntar a malta, jogar mais uma partida e voltar no dia seguinte. Entre chamadas, rounds e aquela competitividade que existe entre amigos, surgiu a ideia de dar um nome ao grupo: SHUSH.</p><p>O nome ficou. O que começou como vontade de jogar em conjunto tornou-se uma identidade para representar quem está dentro do servidor e quem cria conteúdo fora dele. Não somos um projeto feito de promessas grandiosas. Somos as pessoas que fazem a SHUSH acontecer.</p></div></section><section className="about-manifesto" aria-labelledby="identity-title"><span className="section-kicker">02 / Identidade</span><div><h2 id="identity-title">Sem barulho.<br /><span>Só rounds.</span></h2><p>Dentro do servidor, os jogadores. Fora dele, os creators e a camisola. A SHUSH liga estas partes com a mesma identidade.</p></div></section>
        <div className="about-paths"><AppLink href="/esports/valorant/roster"><span className="mono">02 / A equipa</span><strong>Quem joga.</strong><span>Conhecer o roster</span><span aria-hidden="true">↗</span></AppLink><AppLink href="/content"><span className="mono">03 / Os creators</span><strong>Quem cria.</strong><span>More + Th0maz7</span><span aria-hidden="true">↗</span></AppLink><AppLink href="/products/jersey"><span className="mono">04 / A camisola</span><strong>O que nos liga.</strong><span>Explorar Drop 01</span><span aria-hidden="true">↗</span></AppLink></div>
        <section id="partners" className="about-partner" aria-labelledby="partner-title"><span className="section-kicker">05 / Parceiro técnico + digital</span><div className="partner-content"><img src="/assets/brand/backora-logo.png" width="320" height="293" alt="" loading="lazy" decoding="async" /><div><h2 id="partner-title">Backora.</h2><p>Estrutura web e suporte técnico da SHUSH.</p></div><Button href="https://backora.org/" target="_blank" rel="noopener noreferrer" variant="secondary">Conhecer Backora</Button></div></section>
        <section className="about-brand-download" aria-labelledby="brand-title"><div><span className="section-kicker">06 / Marca</span><h2 id="brand-title">A nossa assinatura.</h2><p>Logótipo SHUSH · WebP · 1167 × 647</p></div><Button href="/assets/brand/shush-logo.webp" download="shush-logo.webp" variant="secondary">Descarregar logótipo (WebP)</Button></section>
      </div>
    </section>
  );
}
