import { creators, players } from '../../data/players';
import { AppLink } from '../ui/AppLink';
import { Button } from '../ui/Button';

export function AboutSection() {
  return (
    <section id="about" className="about-page" aria-labelledby="about-title">
      <div className="shell">
        <div className="about-opening"><div><span className="section-kicker">About / SHUSH</span><h1 id="about-title">Antes da SHUSH,<br /><span>já éramos nós.</span></h1></div><div className="about-brand-panel"><div className="about-brand-image"><img src="/assets/brand/shush-logo.webp" width="1167" height="647" alt="Logótipo SHUSH" decoding="async" /></div><p>Um grupo de amigos, vontade de jogar e a conversa que continuava depois da última partida. Foi aí que a SHUSH começou a ganhar forma.</p><div className="about-counts"><span><strong>{players.length}</strong> jogadores</span><span><strong>{creators.length}</strong> creators</span></div></div></div>
        <section className="about-chapters" aria-label="A história da SHUSH"><article><span className="section-kicker">01 / O lobby</span><h2>Mais uma?</h2><p>Era uma pergunta simples. Ficávamos para outra partida, trocávamos ideias e ríamos do round anterior. Sem um grande plano, estávamos a criar uma coisa nossa: um lugar onde apetecia voltar.</p></article><article><span className="section-kicker">02 / O nome</span><h2>A ligação ganhou forma.</h2><p>A vontade de competir trouxe outra intenção ao grupo. Um nome para representar, uma equipa para construir e uma identidade que levássemos connosco para cada servidor.</p></article><article><span className="section-kicker">03 / O que fica</span><h2>Continuar juntos.</h2><p>A SHUSH vive dessa mistura: amizade, competição e vontade de fazer melhor. Os jogadores e os creators dão-lhe voz. O nome lembra-nos que estamos a construir isto em conjunto.</p></article></section>
        <div className="about-people" aria-label="Pessoas da SHUSH">{players.filter(player => player.avatar).map(player => <AppLink key={player.id} href={`/esports/valorant/roster?player=${player.id}`} aria-label={`Conhecer ${player.displayName}`}><img src={player.avatar} alt="" width="768" height="768" loading="lazy" decoding="async" /><span>{player.displayName}</span></AppLink>)}</div>
        <section className="about-manifesto" aria-labelledby="identity-title"><span className="section-kicker">04 / O nosso manifesto</span><div><h2 id="identity-title">Sem barulho.<br /><span>Só rounds.</span></h2><p>Jogar com intenção. Dar espaço a cada pessoa. Levar a competição a sério e saber porque começámos. O próximo round importa — quem está connosco também.</p></div></section>
        <div className="about-paths"><AppLink href="/esports/valorant/roster"><span className="mono">A equipa</span><strong>Quem joga.</strong><span>Conhecer o roster</span><span aria-hidden="true">↗</span></AppLink><AppLink href="/content"><span className="mono">Os creators</span><strong>Quem cria.</strong><span>More + Th0maz7</span><span aria-hidden="true">↗</span></AppLink><AppLink href="/products/jersey"><span className="mono">A camisola</span><strong>O que nos liga.</strong><span>Explorar Drop 01</span><span aria-hidden="true">↗</span></AppLink></div>
        <section id="partners" className="about-partner" aria-labelledby="partner-title"><span className="section-kicker">05 / Parceiro técnico + digital</span><div className="partner-content"><img src="/assets/brand/backora-logo.png" width="320" height="293" alt="" loading="lazy" decoding="async" /><div><h2 id="partner-title">Backora.</h2><p>Estrutura web e suporte técnico da SHUSH.</p></div><Button href="https://backora.org/" target="_blank" rel="noopener noreferrer" variant="secondary">Conhecer Backora</Button></div></section>
        <section className="about-brand-download" aria-labelledby="brand-title"><div><span className="section-kicker">06 / Marca</span><h2 id="brand-title">A nossa assinatura.</h2><p>Logótipo SHUSH · WebP · 1167 × 647</p></div><Button href="/assets/brand/shush-logo.webp" download="shush-logo.webp" variant="secondary">Descarregar logótipo (WebP)</Button></section>
      </div>
    </section>
  );
}
